# Zsh
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# unix utils
brew 'htop-osx'
brew 'docker'
brew 'nmap'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'md5sha1sum'
brew 'ngrep'

# ruby
brew 'rbenv'
brew 'ruby-build'

# build
brew 'coreutils'

# ansible
brew 'ansible'
brew 'fig'

# bin
brew 'node'
brew 'npm'
brew 'packer'

# casks
brew 'caskroom/cask/brew-cask'
brew 'brew-cask'

# apps
cask 'google-chrome'
cask '1password'
cask 'iterm2'
cask 'sourcetree'
cask 'eclipse-jee'
cask 'mamp'
cask 'evernote'
cask 'moom'
cask 'sequel-pro'
cask 'skype'
cask 'virtualbox'
cask 'vagrant'
cask 'hipchat'
cask 'kindle'

tap 'caskroom/homebrew-versions'
cask 'sublime-text3'
cask 'firefox-de'

# install fonts
tap 'caskroom/homebrew-fonts'
cask 'font-hack'
cask 'font-abel'
cask 'font-aclonica'

# Dev Tools
brew 'groovy'
brew 'grails'

# XSITE Tools
cask 'java'
brew 'elasticsearch'
